dataSources:
  - dataSourceKey: mysql_czy_test
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.230.187:3306/question?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrievalx=true
    userName: root
    password: chen
    maxConnectNum: 20
    maxFreeConnectNum: 5
redis:
  config-name: jedisPoolConfig
  pool-name: jedisPool
  host: 106.54.230.187
  port: 6379
  password: chenzy
  database: 0 #Redis数据库索引（默认为0）
  lettuce:
    pool:
      max-idle: 300 #连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接
      max-active: 600 #连接池最大连接数（使用负值表示没有限制）
      max-wait: 1000ms #最大的等待时间，如果超过等待时间，则直接抛出JedisConnectionException；
      time-between-eviction-runs:
  timeout: 1000ms #超时时间
